;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 22/05/2010 11:06:40
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0025	$	_soma:
;portalogica_teste.c,41 :: 		int soma(int a, int b)
;portalogica_teste.c,43 :: 		return (a + b);
$0025	$1303			BCF	STATUS, RP1
$0026	$1283			BCF	STATUS, RP0
$0027	$0822			MOVF	FARG_soma+2, 0
$0028	$0720			ADDWF	FARG_soma+0, 0
$0029	$00F0			MOVWF	STACK_0
$002A	$0821			MOVF	FARG_soma+1, 0
$002B	$1803			BTFSC	STATUS, C
$002C	$3F01			ADDLW	1
$002D	$0723			ADDWF	FARG_soma+3, 0
$002E	$00F1			MOVWF	STACK_0+1
;portalogica_teste.c,44 :: 		}
$002F	$0008			RETURN
$0004	$	_main:
;portalogica_teste.c,10 :: 		void main()
;portalogica_teste.c,14 :: 		TRISA = 0x03;
$0004	$3003			MOVLW	3
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;portalogica_teste.c,15 :: 		TRISB = 0x00;
$0008	$0186			CLRF	TRISB, 1
;portalogica_teste.c,16 :: 		TRISC = 0x00;
$0009	$0187			CLRF	TRISC, 1
;portalogica_teste.c,17 :: 		TRISD = 0x00;
$000A	$0188			CLRF	TRISD, 1
;portalogica_teste.c,18 :: 		TRISE = 0x00;
$000B	$0189			CLRF	TRISE, 1
;portalogica_teste.c,19 :: 		ADCON1= 0X07;    //PORTA e PORTE digitais
$000C	$3007			MOVLW	7
$000D	$009F			MOVWF	ADCON1
;portalogica_teste.c,23 :: 		PORTB = letra;
$000E	$3035			MOVLW	53
$000F	$1283			BCF	STATUS, RP0
$0010	$0086			MOVWF	PORTB
;portalogica_teste.c,25 :: 		PORTC = (char) soma(1025, 2356); //o PORTC fica com  o byte LOW
$0011	$3001			MOVLW	1
$0012	$00A0			MOVWF	FARG_soma+0
$0013	$3004			MOVLW	4
$0014	$00A1			MOVWF	FARG_soma+1
$0015	$3034			MOVLW	52
$0016	$00A2			MOVWF	FARG_soma+2
$0017	$3009			MOVLW	9
$0018	$00A3			MOVWF	FARG_soma+3
$0019	$2025			CALL	_soma
$001A	$0870			MOVF	STACK_0, 0
$001B	$0087			MOVWF	PORTC
;portalogica_teste.c,27 :: 		while (PORTA.f1) //loop infinito
$001C	$	L_main_0:
$001C	$1C85			BTFSS	PORTA, 1
$001D	$2824			GOTO	L_main_1
;portalogica_teste.c,29 :: 		if(PORTA.f0) PORTB.f1=1;
$001E	$1C05			BTFSS	PORTA, 0
$001F	$2822			GOTO	L_main_2
$0020	$1486			BSF	PORTB, 1
$0021	$2823			GOTO	L_main_3
$0022	$	L_main_2:
;portalogica_teste.c,30 :: 		else       PORTB.f1=0;
$0022	$1086			BCF	PORTB, 1
$0023	$	L_main_3:
;portalogica_teste.c,32 :: 		}
$0023	$281C			GOTO	L_main_0
$0024	$	L_main_1:
;portalogica_teste.c,35 :: 		}
$0024	$2824			GOTO	$
