;  ASM code generated by mikroVirtualMachine for PIC - V. 8.1.0.0
;  Date/Time: 21/05/2010 21:21:23
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;teste_mikroc81.c,9 :: 		void main()
;teste_mikroc81.c,11 :: 		TRISA = 0x00;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0185			CLRF	TRISA, 1
;teste_mikroc81.c,13 :: 		}
$0007	$2807			GOTO	$
